### ISSUE TITLE
Active Alert map does not display on mobile device

### ISSUE THREAD

**Issue by roseline1** [betterangels/better-angels#93] opened 2015-12-20 03:34 UTC
The tracking map (under Active Alert for the "alerter" and the chat room for responders) has failed to display on the mobile device I use despite several attempts hitting the buttons: "show map" and "hide map." However, the map successfully displays on PC.

**Comment by meitar** [comment] 2015-12-20 03:58
> the mobile device I use

You'll need to be more specific than that…?

**Comment by roseline1** [comment] 2015-12-20 04:02
*iPhone 4S* to be specific

**Comment by meitar** [comment] 2015-12-20 04:26
Browser?

Consider reading http://noverse.com/blog/2012/06/how-to-write-a-good-bug-report/

**Comment by roseline1** [comment] 2015-12-29 16:38
I apologize for my late response. The browser is Safari version 600.1.4 for iOS

**Comment by meitar** [comment] 2016-01-01 01:24
What are the steps to reproduce the issue? (Again, see [the noverse.com guide to writing a good bug report](http://noverse.com/blog/2012/06/how-to-write-a-good-bug-report/).)

**Comment by roseline1** [comment] 2016-01-04 10:08
The bug occurred every time using Buoy on Safari version 600.1.4 for iOS.
I clicked on the "Show Map" icon in my team's emergency chat room.
I expected to see a "google map" pinpointing my location and that of my other team member.
Rather, I saw a "blank square/space" at the top of the screen which was supposed to contain a map.

**Comment by meitar** [comment] 2016-01-04 10:24
I don't think you're understanding the question I'm asking. The question is "what are the steps to reproduce this issue?"

You say "you click on the 'Show Map' icon in my team's emergency chat room". Okay, what did you before that? And what did you do before that? And what did you do before that? And what did you do before that? Start from the very first thing, starting from "I turned on my iPhone by pressing the power button" if need be, and then provide as much detail as possible about each step.

I can't reproduce the issue if the only step you report is the step in which the problem the occurs.

**Comment by meitar** [comment] 2016-04-05 06:26
This hasn't proved to be a useful issue report and since we're reorganizing the repository structure anyway, I'm gonna close this issue out for now. If it crops up again we can just handle it anew.

**Closed by meitar** 2016-04-05 06:26 UTC
Labels: bug, component:map, question, state:unconfirmed
